import { Inter } from 'next/font/google';
import Link from 'next/link';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="mx-auto max-w-screen-sm">
          <div className="text-lg py-10">
            <Link href="/">my blog</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
